[package]
name = "ctp-sys"
version = "0.1.0"
edition = "2021"
publish = ["../traderapi/**/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }